### ISSUE TITLE
Dep versions

### ISSUE THREAD

**Issue by vxbinaca** [gdamdam/iagitup#9]
Do we need fixed versions for all these packages? `internetarchive` is locked a 1.5.0, `jsonpatch` is ancient at 0.4. I want to start dropping the firm version requirements for some/most/all of these packages.

I'm going to start bumping things and doing PRs.

Edit: After testing of course.

**Comment by gdamdam** [comment]
thank you! good idea.
I dont know if we need fixed versions, probably not really.

**Comment by vxbinaca** [comment]
Actually another part of what I want to do is drop all the locked dep versions and just switch to a `pip install` command but I need to test everything first. I'll take one successful upload as proof it working and send a PR once I can get around to doing this.
